# Generated by Django 3.2.6 on 2021-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='copons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnumber', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'phonenumberlist',
            },
        ),
        migrations.DeleteModel(
            name='coupons',
        ),
    ]
