# Generated by Django 3.2.6 on 2021-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copon', '0002_auto_20210915_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='copons',
            name='cname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
