# Generated by Django 3.2.6 on 2021-11-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copon', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=28)),
                ('customer_email', models.CharField(blank=True, max_length=23)),
                ('payment_id', models.CharField(blank=True, max_length=49)),
            ],
            options={
                'db_table': 'payment_info',
            },
        ),
        migrations.CreateModel(
            name='Payment_details_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(blank=True, max_length=20)),
                ('phonenumber', models.CharField(blank=True, max_length=23)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('paymentstatus', models.CharField(blank=True, max_length=20)),
                ('paymentid', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Payment_details_customer',
            },
        ),
        migrations.CreateModel(
            name='Subscription_details',
            fields=[
                ('sname', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('customer_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'Subscription_details',
            },
        ),
    ]
