# Generated by Django 3.2.6 on 2021-11-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copon', '0005_payment_details_payment_details_customer_subscription_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_details',
            name='sub_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription_details',
            name='customer_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='subscription_details',
            name='email',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
