# Generated by Django 3.2.6 on 2021-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copon', '0006_auto_20211125_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_details',
            name='sub_status',
        ),
        migrations.AlterField(
            model_name='subscription_details',
            name='customer_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription_details',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
